apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafkasql-journal
  labels:
    strimzi.io/cluster: {{ streams_kafka_cluster_name }}
spec:
  partitions: 2
  replicas: 1
  config:
    cleanup.policy: compact