apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: movies
  namespace: kafka-cluster
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: movies
